### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Didoul35** [kosch104/CS2-CustomAssetPack#1]
hello, I have a problem, when I launch the game with your mod, I get lots of errors, and when I load a map I have no roads and the game crashes. an idea ?

https://github.com/kosch104/CS2-CustomAssetPack/assets/102223840/3ebeca11-86c2-4fca-95b2-74ef68e78d3b

**Comment by khallmark** [comment]
@Didoul35 Can you please click the copy icon in the top right of the text box to copy the error then paste it into this issue? 

In a separate comment, please list the mods you have installed besides this one. 

Finally, does this issue only happen when this mod is enabled?

**Comment by Didoul35** [comment]
I don"t use another mod - Error : 

[object Object]
NullReferenceException: Object reference not set to an instance of an object
  at Colossal.IO.AssetDatabase.PrefabAsset+PrefabReferenceResolver.TryResolveReference (System.String id, System.Object& value) [0x00052] in <7fd057c87c1c4e79877a7ca742818d3f>:0 
  at Colossal.OdinSerializer.DeserializationContext.GetExternalObject (System.String id) [0x00033] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
  at Colossal.OdinSerializer.AnySerializer.ReadValueWeak (Colossal.OdinSerializer.IDataReader reader) [0x006df] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
  at Colossal.OdinSerializer.ReflectionFormatter`1[T].DeserializeImplementation (T& value, Colossal.OdinSerializer.IDataReader reader) [0x0013d] in <d9cab27576e9499db8aa70c41ecc0a40>:0 
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Colossal.OdinSerializer.CustomLogger:LogException(Exception)
Colossal.OdinSerializer.DebugContext:LogException(Exception)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(NetSubObjectInfo&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ArrayFormatter`1:DeserializeImplementation(NetSubObjectInfo[]&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(NetSubObjects&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ListFormatter`1:DeserializeImplementation(List`1&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(RoadPrefab&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(Stream, DataFormat, DeserializationContext)
Colossal.IO.AssetDatabase.PrefabAsset:Load()
Game.SceneFlow.GameManager:LoadPrefabs()
Game.SceneFlow.<Initialize>d__60:MoveNext()
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by Didoul35** [comment]
HI ! I fix it, i just restart my games 3 

thank!
