### ISSUE TITLE
Asset packs manager mod problem

### ISSUE THREAD

**Issue by Didoul35** [kosch104/CS2-CustomAssetPack#2]
Hello, for a few days, it has been impossible to download the asset packs manager mod required to make your mod work, consequently, the mod no longer works, could you do what is necessary please,
![Capture d'écran 2024-04-28 143324](https://github.com/kosch104/CS2-CustomAssetPack/assets/102223840/4c20320b-cafe-48b8-a9fc-1241264f032e)

**Comment by kosch104** [comment]
Could you attach the logs of your game please? I need them to investigate the issue. Also, this is not the correct location for a support request, please ask in the discord or on https://github.com/kosch104/CS2-AssetPacksManager
I will still try to assist you here though.
